import Head from 'next/head'
// import { BsFillMoonStarsFill } from 'react-icons/bs';
import { TbPlant2, TbPlant } from 'react-icons/tb';
import { GiPlantRoots } from 'react-icons/gi';
import { AiFillClockCircle } from 'react-icons/ai';
import Image from "next/image";
import monty from "../public/monstera-transparent.png";
import randy from "../public/randall-logo-transparent.png";
import monst from "../public/monstera-tropic.jpeg";
import bird from "../public/bird-tropic.jpeg";
import palm from "../public/plant.jpeg";
import { Inter } from 'next/font/google';
import { useState } from 'react';
import { motion } from 'framer-motion';




const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [isOn, setIsOn] = useState(false);
  const toggleSwitch = () => setIsOn(!isOn);
  const [darkMode, setDarkMode] = useState(false);
  const toggleDarkMode = () => setDarkMode(!darkMode);

  const buttonClick = () => {
    toggleSwitch();
    toggleDarkMode();
  };

  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Randall's Plants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=" md:px-20 lg:px-40 min-h-fit bg-slate-200 px-10 dark:bg-slate-900">
          <nav className="py-5 mb-12 flex justify-between">
            <div>
              <Image src={randy} width={250} height={250} />
            </div>
            <ul className="flex items-center">
              <div className="switch" data-isOn={isOn} onClick={buttonClick}>
                <motion.div className=" handle cursor-pointer text-2xl dark:text-white" layout transition={spring} />
              </div>
              <li><a className=" bg-gradient-to-r from-green-900 to-green-600 font-medium text-white px-4 py-2 rounded-md ml-8 md:text-xl" href="#plants">Plants</a></li>
            </ul>
          </nav>
          <div className=" mx-auto bg-gradient-to-b from-orange-400 rounded-full w-80 h-80 z-1 dark:from-purple-700 bg-gradient-to-b">
            <Image src={monty} />
          </div>
          <div className=" text-center p-1">
            <h1 className=" text-7xl text-green-950 dark:text-green-700 font-bold pt-20">Randall's Plants</h1>
            <h3 className=" text-2xl font-medium pt-8 dark:text-white">Bringing you the best houseplants and homemade pottery</h3>
            <p className=" text-md py-5 leading-8 text-gray-800 dark:text-white md:text-xl max-w-xl mx-auto">We have a wide variety of houseplants ranging from small succulents to large tropical plants. Come by our shop today to see our latest and greatest!</p>
          </div>
          <div className=" text-6xl flex justify-center gap-16 pb-10">
            <div className=" flex justify-evenly bg-gradient-to-b from-orange-400 rounded-full w-16 h-16 z-1 dark:from-purple-700 bg-gradient-to-b dark:text-white">
              <GiPlantRoots />
            </div>
            <div className=" flex justify-evenly bg-gradient-to-b from-orange-400 rounded-full w-16 h-16 z-1 dark:from-purple-700 bg-gradient-to-b dark:text-white">
              <TbPlant2 />
            </div>
            <div className=" flex justify-evenly bg-gradient-to-b from-orange-400 rounded-full w-16 h-16 z-1 dark:from-purple-700 bg-gradient-to-b dark:text-white">
              <TbPlant />
            </div>
          </div>
        </section>
        <section className=" md:px-20 lg:px-40 bg-white px-10 pb-10 dark:bg-slate-800">
          <div>
            <div className=" text-center md:max-w-l mx-auto">
              <h2 id="plants" className=" text-5xl text-green-900 font-bold pt-10 dark:text-green-700">New Plants</h2>
              <h3 className=" text-xl py-5 dark:text-white">Our most recent shipment of tropical house plants:</h3>
            </div>
            <div className=" text-center md:flex justify-center gap-10 max-w-l mx-auto ">
              <div className=" shadow-xl py-10 mb-5 rounded-xl my-10 dark:bg-white">
                <h3 className=" text-2xl font-medium py-5">Majesty Palm</h3>
                <Image className=" mx-auto mb-5" src={palm} width={300} height={300} />
                <a className="bg-gradient-to-r from-green-900 to-green-600 text-white rounded p-2">Only Available In-store</a>
              </div>
              <div className=" shadow-xl py-10 mb-5 rounded-xl my-10 dark:bg-white">
                <h3 className=" text-2xl font-medium py-5">Bird of Paradise</h3>
                <Image className=" mx-auto mb-5" src={bird} width={300} height={300} />
                <a className="bg-gradient-to-r from-green-900 to-green-600 text-white rounded p-2">Only Available In-store</a>
              </div>
              <div className=" shadow-xl py-10 mb-5 rounded-xl my-10 dark:bg-white">
                <h3 className=" text-2xl font-medium py-5">Monstera Deliciosa</h3>
                <Image className=" mx-auto mb-5" src={monst} width={300} height={300} />
                <a className="bg-gradient-to-r from-green-900 to-green-600 text-white rounded p-2">Only Available In-store</a>
              </div>
            </div>
          </div>
        </section>
        <section className=" md:px-20 lg:px-40 bg-slate-200 px-10 pb-10 dark:bg-slate-900">
          <div>
            <div className=" text-center md:max-w-l mx-auto">
              <h2 className=" text-5xl text-green-900 font-bold pt-10 dark:text-green-700">Location</h2>
              <h3 className="text-xl py-5 dark:text-white">Come check out what Ottawa's best plant shop has to offer!</h3>
            </div>
            <div className=" md:flex justify-center gap-10 max-w-l mx-auto">
              <div className="google-map-code flex justify-center">
                <iframe src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=4228%20NAVAN%20RD.%20%20NAVAN,%20ON%20%20K4B%201H9+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" width="300" height="350" frameborder="0" style={{ border: 0 }} allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
              </div>
              <div className='text-center'>
                <div className="flex justify-center mt-10 text-center">
                  <AiFillClockCircle className=" text-green-600 text-2xl mr-2" />
                  <h3 className="text-2xl dark:text-white">Hours:</h3>
                </div>
                <ul className="list-none mb-10">
                  <li className=" text-lg font-medium dark:text-white"> <span className=' text-green-700'>MONDAY</span> 9:00 AM - 6:00 PM</li>
                  <li className=" text-lg font-medium dark:text-white"><span className=' text-green-700'>TUESDAY</span> 9:00 AM - 6:00 PM</li>
                  <li className=" text-lg font-medium dark:text-white"><span className=' text-green-700'>WEDNESDAY</span> 9:00 AM - 6:00 PM</li>
                  <li className=" text-lg font-medium dark:text-white"><span className=' text-green-700'>THURSDAY</span> 9:00 AM - 6:00 PM</li>
                  <li className=" text-lg font-medium dark:text-white"><span className=' text-green-700'>FRIDAY</span> 9:00 AM - 6:00 PM</li>
                  <li className=" text-lg font-medium dark:text-white"><span className=' text-green-700'>SATURDAY</span> 9:00 AM - 5:00 PM</li>
                  <li className=" text-lg font-medium dark:text-white"><span className=' text-green-700'>SUNDAY</span> 9:00 AM - 5:00 PM</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

const spring = {
  type: "spring",
  stiffness: 900,
  damping: 90
};